title: Monkey Patch
description: JavaScript, thoughts and tech.
author: Daniel Daza

# General Info for the site
social:
  github: ddaza
  rss: monkey # just type anything here for a working RSS icon
  twitter: dpdaza

url: https://www.monkeypatch.xyz
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

autoprefixer:
  browsers:
  - last 2 versions

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-feed # rss
  - jekyll-autoprefixer

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: ""
